name: update map

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00 every night
  workflow_dispatch:
    inputs:
      tags:
        description: "testing"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: get key
        env:
          SECRET_JSON: ${{ secrets.GA_JSON }}
        run: |
          echo $SECRET_JSON > secret.json
      
      - name: ingest google analytics data and update db
        run: |
          analytics2map ingest-ga --config-path config/prod.yml --verbose

      - name: clean
        run: rm secret.json

      - name: generate updated plot
        run: analytics2map render --config-path config/prod.yml

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated plot" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
